$schema: http://json-schema.org/draft-07/schema#
$id: hasLocation.schema.json
title: Has Location
description: Location information for an entity
type: object
properties:

  location_indentifier:
    $ref: './locationIdentifier.yaml'

