# Names Configuration Schema
# This schema defines the structure for names configurations in the simulation.

$schema: "http://json-schema.org/draft-07/schema#"
title: Names
version: 1.0
description: Contain
type: object
names:
  type: object
  description: Full Names Configuration
  properties:
    first_name:
      type: string
      description: First names with sex information.
      items:
        type: object
        properties:
          name:
            type: string
            description: The first name.
    last_name:
      type: array
      description: List of last names.
      items:
        type: string
    sex:
      type: string
      enum:
        - male
        - female
        - unisex
      description: The sex associated with the name.
    
