$schema: http://json-schema.org/draft-07/schema#
$id: ownership.schema.json
title: Ownership
type: object
additionalProperties: false
properties:
  owner_id:
    type: string
  permit:
    type: string
    enum:
    - private
    - shared
    - public
